### ISSUE TITLE
Error: Failed to launch chrome! spawn ./../../Google/chrome-mac/Chromium.app/Contents/MacOS/Chromium ENOENT

### ISSUE THREAD

**Issue by solvep** [nicejade/toss-puppeteer#4]
(node:18291) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome! spawn ./../../Google/chrome-mac/Chromium.app/Contents/MacOS/Chromium ENOENT

您好，关于使用puppeteer-core是否需要自己在目录中下载Chromium

**Comment by nicejade** [comment]
@solvep 

从 [puppeteer-core](https://www.npmjs.com/package/puppeteer-core) 的介绍来看，时无需下载 Chromium，而是基于本地的 Chrome，但之前这边没有成功，就还是下载 Chromium 于本地。

>Since version 1.7.0 we publish the puppeteer-core package, a version of Puppeteer that doesn't download any browser by default.

**Comment by solvep** [comment]
@nicejade 
感谢您🙏

**Comment by nicejade** [comment]
@solvep 客气了🤝。
